### ISSUE TITLE
CRA serving html instead of wasm

### ISSUE THREAD

**Issue by savaughn** [bobbiec/react-wasm-demo#1]
Great guide! Thank you for putting this together. I got it working 100%, and I was updating my app when suddenly chrome started throwing an error about memory. I was not free'ing a malloc'd pointer while developing. I closed down the bundle/tab, added a free, and restarted the server, but was met with this error on the next js hot reload.

```
bundle.js:41193 wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response 
bundle.js:41194 falling back to ArrayBuffer instantiation
bundle.js:41182 failed to asynchronously prepare wasm: CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 
bundle.js:41141 Aborted(CompileError: WebAssembly.instantiate(): expected magic word 00 61 73 6d, found 3c 21 44 4f @+0)
```

I reverted my changes back to my last working state, but the error persists. I deployed [this last working state to github pages](https://savaughn.github.io/pksav-viewer) where it serves the wasm with application/wasm type, but for some reason suddenly local is fetching as a document instead.

local
![image](https://github.com/bobbiec/react-wasm-demo/assets/25937456/349288dd-f497-4f5d-b28d-59fb3016b685)
![image](https://github.com/bobbiec/react-wasm-demo/assets/25937456/4f92c99c-ddd1-41a4-a4a2-f2875255f6ab)

github pages
![image](https://github.com/bobbiec/react-wasm-demo/assets/25937456/a9fb16ba-0f47-455e-bd8a-0b66dd108473)

**Things I tried**

- cleared my browser cache on chrome
- restarted chrome
- tried safari
- deleted and recompiled the .mjs/.wasm
- restarted my computer
- cloned my repo to a new folder
- created a new react project with `npx create-react-app`, copied my contents except node_modules to the new react app
- loaded served page on my tablet

Everything was working fine. I was actively using my c code to fetch data from a gameboy save file using [pksav](https://github.com/savaughn/pksav). I see that it's serving the wasm up as an html instead and breaking. Reading your guide, you mentioned specifically fixing this issue, but it seems to have randomly came back.

Any chance you might know what the issue here is?

**Comment by bobbiec** [comment]
Hey @savaughn, it's hard to say without looking at your code.

In general, this kind of behavior happens when the the URL (in this case, `/pksav.wasm`) is handled by your app, which responds with some default HTML. In the guide, we move the .wasm file into the `public` folder to indicate that it should be not webpacked, and so it will be served as a static file. Can you check if you've done this?

Otherwise, if you could share more code, that would help.

**Comment by savaughn** [comment]
Oh sorry, I should have linked my repo [pksav-viewer](https://github.com/savaughn/pksav-viewer). I do have the wasm directly in the public folder. I have a screenshot of it working from last night.
![image](https://github.com/bobbiec/react-wasm-demo/assets/25937456/7d35235f-e2fc-4eed-8689-8450ca36a08f)
I didn't even close my computer, restart anything, or update anything before the error popped up.

**Comment by savaughn** [comment]
I reverted all the way back to just the create react app and imported the createModule. I pushed a [min example branch](https://github.com/savaughn/pksav-viewer/tree/minimum-example).

![image](https://github.com/bobbiec/react-wasm-demo/assets/25937456/47fa659c-de7c-4b7a-ad84-afeeb7c7f380)


```
src/pksav.mjs: src/pksav.c
	emcc --no-entry src/pksav.c -o src/pksav.mjs  \
	  --pre-js src/locateFile.js  \
	  -Iinclude -L../pksav/build-wasm/lib -lpksav  \
	  -s ENVIRONMENT='web'  \
	  -s EXPORT_NAME='createModule'  \
	  -s USE_ES6_IMPORT_META=0  \
	  -s FORCE_FILESYSTEM=1  \
	  -s EXPORTED_FUNCTIONS='["_malloc", "_free"]'  \
	  -s EXPORTED_RUNTIME_METHODS='["ccall", "cwrap"]'  \
	  -O3
```

**Comment by savaughn** [comment]
EDIT: This only worked, because homepage was no longer set in my package json. [SOLUTION](https://github.com/bobbiec/react-wasm-demo/issues/1#issuecomment-1955640311)

I fixed it! 🥳 
I changed package.json dependencies removing any "^". One `npm install` later, and everything works again!

Here's my dependency list:
```js
"dependencies": {
    "@testing-library/jest-dom": "5.17.0",
    "@testing-library/react": "13.4.0",
    "@testing-library/user-event": "13.5.0",
    "react": "18.2.0",
    "react-dom": "18.2.0",
    "react-scripts": "5.0.1",
    "web-vitals": "2.1.4"
  }
  ```

**Comment by savaughn** [comment]
Unfortunately, it randomly came back. It happened after running `npm start`. I think it might something with the path. I noticed when it was working it would list the local address as localhost:3000, and when it's not working it's localhost:3000/pksav-viewer.

**Comment by savaughn** [comment]
So real solution! In create-react-app docs it discusses [public url](https://create-react-app.dev/docs/advanced-configuration/#:~:text=for%20more%20details.-,PUBLIC_URL,-%E2%9C%85%20Used). Where you specify the field "homepage" is also being used by github pages dev package, gh-pages. This collision sometimes 🤷  breaks the local web host. By removing homepage field from package json and running `npm start`, the issue immediately resolved.

In order to still deploy to github, I run set homepage before build and delete homepage after deployment using npm.
```
"homepage:set": "npm pkg set \"homepage\"=\"https://savaughn.github.io/pksav-viewer\"",
"homepage:delete": "npm pkg delete \"homepage\""
 ```
